spring.application.name=DigitalGoldWalletFrontend

# Replace localhost with your system IP
#backend.base-url=http://172.16.160.128:8080
backend.base-url=http://localhost:8080

# Run frontend on this port
server.port=9090

# Allow external access
server.address=0.0.0.0